name: 'Docker registry login'
description: 'Log in to a Docker registry, DockerHub or custom one, depending on inputs with retries'

inputs:
  registry:
    description: 'Registry URL, if not provided defaults to DockerHub'
    required: false
  username:
    description: 'Username for given registry or DockerHub'
    required: false
  password:
    description: 'Password or preferably PAT for "username"'
    required: false
  attempt_limit:
    description: 'Maximum number of total attempts'
    required: false
    default: '3'
  attempt_delay:
    description: 'Delay between attempts'
    required: false
    default: '15'

# NOTE: as short term fix we refer to commit in 'feat/add-retries' branch
# Merging PR will lead to conflicts when we want to sync fork.
# So for long term we should decide how to go there.
runs:
  using: 'composite'

  steps:
    - name: Log in to Docker registry
      uses: neondatabase-labs/docker-login-with-retries-action@810869f3bbbd52c1784a14b06c868bffb13222c9
      with:
        max-attempts: ${{ inputs.attempt_limit }}
        retry-timeout: ${{ inputs.attempt_delay }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        registry: ${{ inputs.registry }}
