[package]
name = "mutexbot"
version = "0.2.2"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
ghactions = { version = "0.13.0", features = ["log", "macros", "generate"], default-features = false }
reqwest = { version = "0.12.12", features = ["json", "default-tls"], default-features = false }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread", "time"] }
