name: "Create release PR"
description: "Create a release PR using neon-release-pr"
inputs:
  component:
    description: "The component to release"
    required: true
  base:
    description: "Base branch"
    required: false
  cherry-pick:
    description: "JSON array of commits to cherry-pick"
    required: false
  auto-merge:
    description: "Enable auto-merge after PR approval"
    required: false
  approve:
    description: "Approve the PR"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      with:
        version: "0.6.16"

    - name: Build neon-release-pr
      shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        uv sync
        uv build

    - name: Run neon-release-pr
      env:
        UV_PROJECT: ${{ github.action_path }}
      shell: bash
      run: |
        set -euo pipefail

        neon_release_pr_args=( )

        if [[ -n "${{ inputs.base }}" ]]; then
          neon_release_pr_args+=( --base "${{ inputs.base }}" )
        fi

        if [[ "${{ inputs.auto-merge }}" == "true" ]]; then
          neon_release_pr_args+=( --auto-merge )
        fi

        if [[ "${{ inputs.approve }}" == "true" ]]; then
          neon_release_pr_args+=( --approve )
        fi

        read -ra commits <<< "${{ inputs.cherry-pick }}"

        neon-release-pr new "${neon_release_pr_args[@]}" "${{ inputs.component }}" "${commits[@]}"
