name: Deploy Queue
description: Action to start, finish and cancel deployments.
inputs:
  mode:
    description: Whether to start, finish or cancel the deployment
    default: reserve
  environment:
    description: Environment where to deploy
    required: true
  cloud-provider:
    description: Cloud provider to deploy
    required: true
  region:
    description: Region to deploy
    required: true
  cell-index:
    description: Cell index to deploy
    required: true
  component:
    description: Component to deploy
    required: true
  version:
    description: Version to deploy
    default: ''
  concurrency-key:
    description: Concurrency key for this deployment
    default: ''
  url:
    description: URL to the specific GitHub Actions job
    default: ''
  note:
    description: Note for this deployment (for manual deployments)
    default: ''
  deployment-id:
    description: Deployment ID (for finish, cancel, info modes)
    default: ''
  cancellation-note:
    description: Cancellation note (for cancel mode)
    default: ''
  slack-channel-id:
    description: Slack channel ID to send notifications to
    default: ''
  slack-bot-token:
    description: Slack bot token to use for sending notifications
    default: ''
  slack-start-message-id:
    description: Slack message ID (timestamp) from the start notification to thread finish/cancel messages (for finish/cancel modes)
    default: ''


outputs:
  deployment-id:
    description: ID of the created deployment (only set for start mode)
    value: ${{ steps.run-deploy-queue.outputs.deployment-id }}
  slack-start-message-id:
    description: Slack message ID (timestamp) of the start notification (only set for start mode with Slack notifications enabled)
    value: ${{ steps.send-slack-start.outputs.ts }}

runs:
  using: "composite"
  steps:
    - name: Detect target triple
      id: triple
      shell: bash
      run: |
        echo "triple=$(uname -m)-unknown-linux-musl" | tee -a "$GITHUB_OUTPUT"

    - name: Resolve action ref to tag
      id: tag
      shell: bash
      run: |
        if [ -z "$REF" ]; then
          echo "Empty github.action_ref, falling back to github.sha assuming local execution"
          REF="${SHA}"
        fi

        if [[ "$REF" =~ ^[0-9a-f]{40}$ ]]; then
          echo "Ref is a commit SHA, resolving to release tag..."

          tag=$(gh api repos/neondatabase/dev-actions/git/matching-refs/tags --paginate | jq -r --arg sha "$REF" 'map(select(.object.sha == $sha)) | first | .ref | ltrimstr("refs/tags/") // error("No release tag found for commit " + $sha)')

          echo "tag=$tag" | tee -a "$GITHUB_OUTPUT"
        else
          echo "tag=$REF" | tee -a "$GITHUB_OUTPUT"
        fi
      env:
        GH_TOKEN: ${{ github.token }}
        REF: ${{ github.action_ref }}
        SHA: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Download deploy-queue binary
      shell: bash
      run: |
        if [ ! -f "${ARCHIVE}.tar.zst" ]; then
          gh release download "$TAG" \
            --repo "$ACTION_REPO" \
            --pattern "$ARCHIVE.tar.zst"

          tar xvf "$ARCHIVE.tar.zst"
        fi

        echo "$(pwd)/${ARCHIVE}" | tee -a "${GITHUB_PATH}"
      working-directory: ${{ github.action_path }}
      env:
        GH_TOKEN: ${{ github.token }}
        TAG: ${{ steps.tag.outputs.tag }}
        ARCHIVE: "deploy-queue-${{ steps.triple.outputs.triple }}"
        ACTION_REPO: ${{ github.action_repository }}

    - name: Run deploy-queue
      id: run-deploy-queue
      shell: bash
      env:
        MODE: ${{ inputs.mode }}
        ENVIRONMENT: ${{ inputs.environment }}
        CLOUD_PROVIDER: ${{ inputs.cloud-provider }}
        REGION: ${{ inputs.region }}
        CELL_INDEX: ${{ inputs.cell-index }}
        COMPONENT: ${{ inputs.component }}
        VERSION: ${{ inputs.version }}
        CONCURRENCY_KEY: ${{ inputs.concurrency-key }}
        URL: ${{ inputs.url }}
        NOTE: ${{ inputs.note }}
        DEPLOYMENT_ID: ${{ inputs.deployment-id }}
        CANCELLATION_NOTE: ${{ inputs.cancellation-note }}
      run: |
        set -euo pipefail

        args=()

        if [[ "${ENVIRONMENT}" == "prod" ]]; then
          args+=("--skip-migrations")
        fi

        case "${MODE}" in
          "start")
            args+=(
              "start"
              "--environment" "${ENVIRONMENT}"
              "--provider" "${CLOUD_PROVIDER}"
              "--region" "${REGION}"
              "--cell-index" "${CELL_INDEX}"
              "--component" "${COMPONENT}"
            )

            # Add optional arguments as flags
            if [[ -n "${VERSION:-}" ]]; then
              args+=("--version" "${VERSION}")
            fi

            # Use provided URL or generate GitHub Actions URL as fallback
            if [[ -n "${URL:-}" ]]; then
              args+=("--url" "${URL}")
            else
              args+=("--url" "Started by ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}")
            fi

            if [[ -n "${NOTE:-}" ]]; then
              args+=("--note" "${NOTE}")
            fi

            if [[ -n "${CONCURRENCY_KEY:-}" ]]; then
              args+=("--concurrency-key" "${CONCURRENCY_KEY}")
            fi

            deploy-queue "${args[@]}"
            ;;
          "finish")
            args+=("finish" "${DEPLOYMENT_ID}")
            deploy-queue "${args[@]}"
            ;;
          "cancel")
            args+=("cancel")

            # Validate input parameters
            if [[ -n "${DEPLOYMENT_ID:-}" ]]; then
              # If deployment-id is set, use it (other params ignored except cancellation-note)
              args+=("${DEPLOYMENT_ID}")
            else
              # If deployment-id is NOT set, validate that we have enough info to identify deployments
              # Option 1: environment + component + version
              # Option 2: environment + provider + region (+ optional cell-index)
              
              has_component_version="${COMPONENT:+1}${VERSION:+1}${ENVIRONMENT:+1}"
              has_location="${ENVIRONMENT:+1}${CLOUD_PROVIDER:+1}${REGION:+1}"
              
              if [[ "${has_component_version}" == "111" ]]; then
                # Valid: component + version + environment are all set
                :
              elif [[ "${has_location}" == "111" ]]; then
                # Valid: environment + provider + region are all set
                :
              else
                echo "Error: Either deployment-id OR (component + version + environment) OR (environment + provider + region) must be set for cancel mode"
                exit 1
              fi

              # Add optional arguments as flags for cancel all deployments
              if [[ -n "${ENVIRONMENT:-}" ]]; then
                args+=("--environment" "${ENVIRONMENT}")
              fi

              if [[ -n "${CLOUD_PROVIDER:-}" ]]; then
                args+=("--provider" "${CLOUD_PROVIDER}")
              fi

              if [[ -n "${REGION:-}" ]]; then
                args+=("--region" "${REGION}")
              fi

              if [[ -n "${CELL_INDEX:-}" ]]; then
                args+=("--cell-index" "${CELL_INDEX}")
              fi

              if [[ -n "${COMPONENT:-}" ]]; then
                args+=("--component" "${COMPONENT}")
              fi

              if [[ -n "${VERSION:-}" ]]; then
                args+=("--version" "${VERSION}")
              fi
            fi

            if [[ -n "${CANCELLATION_NOTE:-}" ]]; then
              args+=("${CANCELLATION_NOTE}")
            fi
            deploy-queue "${args[@]}"
            ;;
          "info")
            args+=("info" "${DEPLOYMENT_ID}")
            deploy-queue "${args[@]}"
            ;;
          *)
            echo "Unknown mode: ${MODE}"
            exit 1
            ;;
        esac

    - name: Send start notification to Slack
      id: send-slack-start
      if: inputs.mode == 'start' && inputs.slack-channel-id != ''
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack-bot-token }}
        payload: |
          {
            "channel": ${{ inputs.slack-channel-id }},
            "text": "🚀 Deployment Started",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ format(
                    '🚀 *Deployment Started* - {0} \n*Component*: {1} {2}\n*Region*: {3}-{4}-{5}-cell-{6}\n*Deployment ID*: {7}',
                    steps.run-deploy-queue.outcome,
                    inputs.component,
                    inputs.version,
                    inputs.environment,
                    inputs.cloud-provider,
                    inputs.region,
                    inputs.cell-index,
                    steps.run-deploy-queue.outputs.deployment-id
                  ) }}
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": ":github: <${{ inputs.url }}|View GitHub Actions Job>"
                  }
                ]
              },
              {
                "type": "divider"
              }
            ]
          }

    - name: Send finish/cancel notification to Slack
      id: send-slack-finish-cancel
      if: (inputs.mode == 'finish' || inputs.mode == 'cancel') && inputs.slack-channel-id != ''
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack-bot-token }}
        payload: |
          {
            "channel": ${{ inputs.slack-channel-id }},
            ${{ inputs.slack-start-message-id != '' && format('"thread_ts": "{0}",', inputs.slack-start-message-id) || '' }}
            "text": "${{ inputs.mode == 'finish' && 'Deployment Finished' || 'Deployment Cancelled' }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ format(
                    '{0} - {1} \n*Deployment ID*: {2}',
                    inputs.mode == 'finish' && '✅ *Deployment Finished*' || '❌ *Deployment Cancelled*',
                    steps.run-deploy-queue.outcome,
                    inputs.deployment-id
                  ) }}
                }
              },
              {
                "type": "divider"
              }
            ]
          }      
