name: Deploy Queue
description: Action to start, finish and cancel deployments.
inputs:
  mode:
    description: Whether to start, finish or cancel the deployment
    default: reserve
  environment:
    description: Environment where to deploy
    required: true
  cloud-provider:
    description: Cloud provider to deploy
    required: true
  region:
    description: Region to deploy
    required: true
  cell-index:
    description: Cell index to deploy
    required: true
  component:
    description: Component to deploy
    required: true
  version:
    description: Version to deploy
    default: ''
  concurrency-key:
    description: Concurrency key for this deployment
    default: ''
  url:
    description: URL to the specific GitHub Actions job
    default: ''
  note:
    description: Note for this deployment (for manual deployments)
    default: ''
  deployment-id:
    description: Deployment ID (for finish, cancel, info modes)
    default: ''
  cancellation-note:
    description: Cancellation note (for cancel mode)
    default: ''

outputs:
  deployment-id:
    description: ID of the created deployment (only set for start mode)
    value: ${{ steps.run-deploy-queue.outputs.deployment-id }}

runs:
  using: "composite"
  steps:
    - name: Detect target triple
      id: triple
      shell: bash
      run: |
        echo "triple=$(uname -m)-unknown-linux-musl" | tee -a "$GITHUB_OUTPUT"

    - name: Resolve action ref to tag
      id: tag
      shell: bash
      run: |
        if [ -z "$REF" ]; then
          echo "Empty github.action_ref, falling back to github.sha assuming local execution"
          REF="${SHA}"
        fi

        if [[ "$REF" =~ ^[0-9a-f]{40}$ ]]; then
          echo "Ref is a commit SHA, resolving to release tag..."

          tag=$(gh api repos/neondatabase/dev-actions/git/matching-refs/tags --paginate | jq -r --arg sha "$REF" 'map(select(.object.sha == $sha)) | first | .ref | ltrimstr("refs/tags/") // error("No release tag found for commit " + $sha)')

          echo "tag=$tag" | tee -a "$GITHUB_OUTPUT"
        else
          echo "tag=$REF" | tee -a "$GITHUB_OUTPUT"
        fi
      env:
        GH_TOKEN: ${{ github.token }}
        REF: ${{ github.action_ref }}
        SHA: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Download deploy-queue binary
      shell: bash
      run: |
        if [ ! -f "${ARCHIVE}.tar.zst" ]; then
          gh release download "$TAG" \
            --repo "$ACTION_REPO" \
            --pattern "$ARCHIVE.tar.zst"

          tar xvf "$ARCHIVE.tar.zst"
        fi

        echo "$(pwd)/${ARCHIVE}" | tee -a "${GITHUB_PATH}"
      working-directory: ${{ github.action_path }}
      env:
        GH_TOKEN: ${{ github.token }}
        TAG: ${{ steps.tag.outputs.tag }}
        ARCHIVE: "deploy-queue-${{ steps.triple.outputs.triple }}"
        ACTION_REPO: ${{ github.action_repository }}

    - name: Run deploy-queue
      id: run-deploy-queue
      shell: bash
      env:
        MODE: ${{ inputs.mode }}
        ENVIRONMENT: ${{ inputs.environment }}
        CLOUD_PROVIDER: ${{ inputs.cloud-provider }}
        REGION: ${{ inputs.region }}
        CELL_INDEX: ${{ inputs.cell-index }}
        COMPONENT: ${{ inputs.component }}
        VERSION: ${{ inputs.version }}
        CONCURRENCY_KEY: ${{ inputs.concurrency-key }}
        URL: ${{ inputs.url }}
        NOTE: ${{ inputs.note }}
        DEPLOYMENT_ID: ${{ inputs.deployment-id }}
        CANCELLATION_NOTE: ${{ inputs.cancellation-note }}
      run: |
        set -euo pipefail

        args=()

        if [[ "${ENVIRONMENT}" == "prod" ]]; then
          args+=("--skip-migrations")
        fi

        case "${MODE}" in
          "start")
            args+=(
              "start"
              "--environment" "${ENVIRONMENT}"
              "--provider" "${CLOUD_PROVIDER}"
              "--region" "${REGION}"
              "--cell-index" "${CELL_INDEX}"
              "--component" "${COMPONENT}"
            )

            # Add optional arguments as flags
            if [[ -n "${VERSION:-}" ]]; then
              args+=("--version" "${VERSION}")
            fi

            # Use provided URL or generate GitHub Actions URL as fallback
            if [[ -n "${URL:-}" ]]; then
              args+=("--url" "${URL}")
            else
              args+=("--url" "Started by ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}")
            fi

            if [[ -n "${NOTE:-}" ]]; then
              args+=("--note" "${NOTE}")
            fi

            if [[ -n "${CONCURRENCY_KEY:-}" ]]; then
              args+=("--concurrency-key" "${CONCURRENCY_KEY}")
            fi

            deploy-queue "${args[@]}"
            ;;
          "finish")
            args+=("finish" "${DEPLOYMENT_ID}")
            deploy-queue "${args[@]}"
            ;;
          "cancel")
            args+=("cancel" "${DEPLOYMENT_ID}")
            if [[ -n "${CANCELLATION_NOTE:-}" ]]; then
              args+=("${CANCELLATION_NOTE}")
            fi
            deploy-queue "${args[@]}"
            ;;
          "info")
            args+=("info" "${DEPLOYMENT_ID}")
            deploy-queue "${args[@]}"
            ;;
          *)
            echo "Unknown mode: ${MODE}"
            exit 1
            ;;
        esac

    - name: Send start notification to Slack
      id: send-slack-start
      if: steps.run-deploy-queue.outcome == 'success' && inputs.mode == 'start' && inputs.environment == 'prod'
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      with:
        channel-id: 'C09QDUK37QW' # channel lakebase-deploy-queue-stream
        payload: |
          {
            "text": "🚀 Deployment Started",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*🚀 Deployment Started*\n*Component*: ${{ inputs.component }}\n*Version*: ${{ inputs.version }}\n*Environment*: ${{ inputs.environment }}\n*Cloud Provider*: ${{ inputs.cloud-provider }}\n*Region*: ${{ inputs.region }}\n*Cell Index*: ${{ inputs.cell-index }}\n*Deployment ID*: ${{ steps.run-deploy-queue.outputs.deployment-id }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    - name: Send finish/cancel notification to Slack
      id: send-slack-finish-cancel
      if: steps.run-deploy-queue.outcome == 'success' && (inputs.mode == 'finish' || inputs.mode == 'cancel') && inputs.environment == 'prod'
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      with:
        channel-id: 'C09QDUK37QW' # channel lakebase-deploy-queue-stream
        payload: |
          {
            "text": "${{ inputs.mode == 'finish' && 'Deployment Finished' || 'Deployment Cancelled' }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ inputs.mode == 'finish' && 'Deployment Finished' || 'Deployment Cancelled' }}\n*Deployment ID*: ${{ inputs.deployment-id }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}        
