name: Deploy Queue

on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]
    branches: ["main"]
    paths: ["deploy-queue/**"]
  push:
    branches: ["main"]
    paths: ["deploy-queue/**"]
    tags: ["deploy-queue-v*.*.*"]

permissions:
  contents: read

env:
  GHCR_REPO: ghcr.io/neondatabase/dev-actions

jobs:
  lint:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: deploy_queue_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/deploy_queue_test
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Fetch deploy-queue folder
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          sparse-checkout: deploy-queue

      - name: Verify migrations work
        working-directory: deploy-queue
        run: |
          # PostgreSQL is already healthy thanks to health checks
          # Install sqlx-cli to run migrations
          cargo install sqlx-cli --no-default-features --features postgres
          
          # Apply migrations to verify they work correctly
          sqlx migrate run
          
          echo "Database migrations completed successfully"

      - name: Verify SQLx query cache is up-to-date
        working-directory: deploy-queue
        run: |
          # Check that the query cache matches current queries
          cargo sqlx prepare --check
          
          echo "SQLx query cache is up-to-date"

      - name: Check code formatting
        working-directory: deploy-queue
        run: |
          # Verify code is properly formatted
          cargo fmt --all -- --check
          
          echo "Code formatting check passed"

      - name: Lint and verify lockfile
        working-directory: deploy-queue
        run: |
          # Run clippy with locked dependencies to ensure lockfile is up-to-date
          cargo clippy --locked --all-targets --all-features -- -D warnings
          
          echo "Linting and lockfile verification completed"

  test:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: deploy_queue_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/deploy_queue_test
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Fetch deploy-queue folder
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          sparse-checkout: deploy-queue

      - name: Setup database and run migrations
        working-directory: deploy-queue
        run: |
          # Install sqlx-cli to run migrations
          cargo install sqlx-cli --no-default-features --features postgres
          
          # Apply migrations for tests
          sqlx migrate run
          
          echo "Database setup completed for tests"

      - name: Run tests
        working-directory: deploy-queue
        run: |
          # Run all tests with output
          cargo test --locked --all-targets --all-features
          
          echo "All tests completed successfully"

  build-image:
    runs-on: ${{ matrix.runner }}
    outputs:
      digest_x86_64: ${{ steps.export_digest.outputs.digest_x86_64 }}
      digest_aarch64: ${{ steps.export_digest.outputs.digest_aarch64 }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Fetch deploy-queue folder
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: deploy-queue

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.GHCR_REPO }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: deploy-queue
          labels: ${{ steps.meta.outputs.labels }}
          attests: |
            type=provenance,mode=max
            type=sbom,generator=docker.io/docker/buildkit-syft-scanner:1
          outputs: type=image,name=${{ env.GHCR_REPO }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        id: export_digest
        run: |
          digest="${{ steps.build.outputs.digest }}"
          echo "digest_$(uname -m)=${digest#sha256:}" | tee -a "$GITHUB_OUTPUT"

  merge-image:
    runs-on: ubuntu-24.04
    needs: [build-image]
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.GHCR_REPO }}
          tags: |
            # branch event
            type=ref,enable=true,priority=600,prefix=deploy-queue-,suffix=,event=branch
            # pull request event
            type=ref,enable=true,priority=600,prefix=deploy-queue-pr-,suffix=,event=pr
            # tags event
            type=match,pattern=deploy-queue-v(.*)

      - name: Create manifest list and push
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            ${{ env.GHCR_REPO }}@sha256:${{ needs.build-image.outputs.digest_aarch64 }} \
            ${{ env.GHCR_REPO }}@sha256:${{ needs.build-image.outputs.digest_x86_64 }}

      - name: Inspect image
        run: docker buildx imagetools inspect ${{ env.GHCR_REPO }}:${{ steps.meta.outputs.version }}

  build-binary:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Fetch deploy-queue folder
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          sparse-checkout: deploy-queue

      - name: Build binary
        working-directory: deploy-queue
        run: |
          TARGET="$(uname -m)-unknown-linux-musl"
          echo "TARGET=${TARGET}" | tee -a "${GITHUB_ENV}"
          rustup target add "${TARGET}"
          sudo apt-get update && sudo apt-get install -y musl-tools musl-dev
          cargo install cargo-auditable --locked
          cargo auditable build --release --target "${TARGET}"
          cp "target/${TARGET}/release/deploy-queue" assets/
          mv assets "deploy-queue-${TARGET}"

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: deploy-queue-${{ env.TARGET }}
          path: deploy-queue/deploy-queue-${{ env.TARGET }}

  create-release:
    needs: [build-binary]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Fetch artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: "!*.dockerbuild"

      - name: Create archives
        run: |
          for artifact in $(ls); do
            chmod a+x "${artifact}/deploy-queue"
            tar cvf "${artifact}.tar.zst" "${artifact}"
          done
          
      - name: Create release from tag
        if: github.ref_type == 'tag'
        run: |
          gh release create "${{ github.ref_name }}" \
            --repo "${GITHUB_REPOSITORY}" \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release for ${{ github.ref_name }}" \
            --verify-tag \
            deploy-queue-*.tar.zst
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update pre-release
        if: github.event_name == 'pull_request'
        run: |
          TAG="deploy-queue-pr-${{ github.event.pull_request.number }}"

          # Delete existing pre-release if it exists
          if gh release view "$TAG" --repo "$GITHUB_REPOSITORY" > /dev/null 2>&1; then
            echo "Deleting existing release $TAG"
            gh release delete "$TAG" \
              --repo "$GITHUB_REPOSITORY" \
              --yes \
              --cleanup-tag
          fi

          gh release create "$TAG" \
            --repo "${GITHUB_REPOSITORY}" \
            --target "${COMMIT_SHA}" \
            --prerelease \
            --title "Pre-release for $TAG" \
            --notes "Pre-release for $TAG" \
            deploy-queue-*.tar.zst
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-deploy-queue-action:
    if: github.event_name == 'pull_request' || github.ref_type == 'tag'
    needs: [create-release]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: deploy_queue_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DEPLOY_QUEUE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/deploy_queue_test
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Fetch deploy-queue folder
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: deploy-queue

      # ==============================================================================
      # Test 1: Complete Happy Path Lifecycle (start → finish)
      # ==============================================================================
      
      - name: Start deployment (happy path test)
        id: start-deployment
        uses: ./deploy-queue
        with:
          mode: start
          region: test-region-happy
          component: test-component-happy
          environment: dev
          version: v1.0.0
          url: https://github.com/test-happy
          note: Happy path test deployment

      - name: Finish the deployment successfully
        uses: ./deploy-queue
        with:
          mode: finish
          deployment_id: ${{ steps.start-deployment.outputs.deployment-id }}

      - name: Verify finished deployment info
        uses: ./deploy-queue
        with:
          mode: info
          deployment_id: ${{ steps.start-deployment.outputs.deployment-id }}

      # ==============================================================================
      # Test 2: Blocking Behavior (same region + component)
      # ==============================================================================

      - name: Start blocking deployment
        id: blocking-deployment
        uses: ./deploy-queue
        with:
          mode: start
          region: test-region-block
          component: test-component-block
          environment: dev
          version: v1.1.0
          url: https://github.com/test-blocking
          note: Blocking deployment test

      - name: Try to start blocked deployment (should fail due to blocking)
        uses: ./deploy-queue
        continue-on-error: true
        timeout-minutes: 1
        with:
          mode: start
          region: test-region-block  # Same region
          component: test-component-block  # Same component → should be blocked
          environment: dev
          version: v1.2.0
          url: https://github.com/test-blocked
          note: Should be blocked deployment

      - name: Finish blocking deployment to unblock
        uses: ./deploy-queue
        with:
          mode: finish
          deployment_id: ${{ steps.blocking-deployment.outputs.deployment-id }}

      # ==============================================================================
      # Test 3: Non-Blocking Behavior (different region)
      # ==============================================================================

      - name: Start deployment in region A
        id: region-a-deployment
        uses: ./deploy-queue
        with:
          mode: start
          region: test-region-a
          component: shared-component
          environment: dev
          version: v2.0.0
          url: https://github.com/test-region-a
          note: Region A deployment

      - name: Start deployment in region B (should NOT be blocked)
        id: region-b-deployment
        uses: ./deploy-queue
        with:
          mode: start
          region: test-region-b  # Different region
          component: shared-component  # Same component but different region
          environment: dev
          version: v2.1.0
          url: https://github.com/test-region-b
          note: Region B deployment (not blocked)

      - name: Finish both regional deployments
        uses: ./deploy-queue
        with:
          mode: finish
          deployment_id: ${{ steps.region-a-deployment.outputs.deployment-id }}

      - name: Finish region B deployment
        uses: ./deploy-queue
        with:
          mode: finish
          deployment_id: ${{ steps.region-b-deployment.outputs.deployment-id }}

      # ==============================================================================
      # Test 4: Cancellation Flow
      # ==============================================================================

      - name: Start deployment for cancellation test
        id: cancel-deployment
        uses: ./deploy-queue
        with:
          mode: start
          region: test-region-cancel
          component: test-component-cancel
          environment: dev
          version: v3.0.0
          url: https://github.com/test-cancel
          note: Cancellation test deployment

      - name: Cancel the deployment
        uses: ./deploy-queue
        with:
          mode: cancel
          deployment_id: ${{ steps.cancel-deployment.outputs.deployment-id }}
          cancellation_note: E2E test cancellation

      - name: Verify cancelled deployment info
        uses: ./deploy-queue
        with:
          mode: info
          deployment_id: ${{ steps.cancel-deployment.outputs.deployment-id }}
