name: Mutexbot

on:
  pull_request:
    types: ["opened", "synchronize", "reopened"]
    branches: ["main"]
    paths: ["mutexbot/**", ".github/workflows/mutexbot*.yml"]
  push:
    branches: ["main"]
    paths: ["mutexbot/**", ".github/workflows/mutexbot*.yml"]
    tags: ["mutexbot-v*.*.*"]

permissions:
  contents: read

jobs:
  build-image:
    uses: ./.github/workflows/build_container_image.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    with:
      registry: ghcr.io  
      name: neondatabase/dev-actions
      tag: >-
        ${{
          (github.event_name == 'pull_request' && format('mutexbot-pr-{0}', github.event.pull_request.number))
          || (github.ref_type == 'tag' && github.ref_name)
          || format('mutexbot-{0}', github.ref_name)
        }}
      context: mutexbot
      dockerfile: mutexbot/Dockerfile
      cache-prefix: mutexbot
      update-cache: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      registry-user: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  build-binary:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Fetch mutexbot folder
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          sparse-checkout: mutexbot

      - name: Build binary
        working-directory: mutexbot
        run: |
          TARGET="$(uname -m)-unknown-linux-musl"
          echo "TARGET=${TARGET}" | tee -a "${GITHUB_ENV}"
          rustup target add "${TARGET}"
          sudo apt-get update && sudo apt-get install -y musl-tools musl-dev
          cargo install cargo-auditable --locked
          cargo auditable build --release --target "${TARGET}"
          cp "target/${TARGET}/release/mutexbot" assets/
          mv assets "mutexbot-${TARGET}"

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: mutexbot-${{ env.TARGET }}
          path: mutexbot/mutexbot-${{ env.TARGET }}

  create-release:
    needs: [build-binary]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Fetch artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: "!*.dockerbuild"

      - name: Create archives
        run: |
          for artifact in $(ls); do
            chmod a+x "${artifact}/mutexbot"
            tar cvf "${artifact}.tar.zst" "${artifact}"
          done
          
      - name: Create release from tag
        if: github.ref_type == 'tag'
        run: |
          gh release create "${{ github.ref_name }}" \
            --repo "${GITHUB_REPOSITORY}" \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release for ${{ github.ref_name }}" \
            --verify-tag \
            mutexbot-*.tar.zst
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or update pre-release
        if: github.event_name == 'pull_request'
        run: |
          TAG="mutexbot-pr-${{ github.event.pull_request.number }}"

          # Delete existing pre-release if it exists
          if gh release view "$TAG" --repo "$GITHUB_REPOSITORY" > /dev/null 2>&1; then
            echo "Deleting existing release $TAG"
            gh release delete "$TAG" \
              --repo "$GITHUB_REPOSITORY" \
              --yes \
              --cleanup-tag
          fi

          gh release create "$TAG" \
            --repo "${GITHUB_REPOSITORY}" \
            --target "${COMMIT_SHA}" \
            --prerelease \
            --title "Pre-release for $TAG" \
            --notes "Pre-release for $TAG" \
            mutexbot-*.tar.zst
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-mutexbot-action:
    if: github.event_name == 'pull_request' || github.ref_type == 'tag'
    needs: [create-release]
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Fetch mutexbot folder
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: mutexbot

      - name: Reserve test-resource as component A
        uses: ./mutexbot
        with:
          api_key: ${{ secrets.MUTEXBOT_API_KEY_TEST_COMPONENT_A }}
          mode: reserve
          resource_name: test-resource
          isolation_channel: ${{ vars.MUTEXBOT_CHANNEL_TESTING }}

      - name: Try (and fail) to reserve test-resource as component B
        uses: ./mutexbot
        continue-on-error: true
        timeout-minutes: 1
        with:
          api_key: ${{ secrets.MUTEXBOT_API_KEY_TEST_COMPONENT_B }}
          mode: reserve
          resource_name: test-resource
          isolation_channel: ${{ vars.MUTEXBOT_CHANNEL_TESTING }}

      - name: Try (and fail) to release as component B
        uses: ./mutexbot
        continue-on-error: true
        timeout-minutes: 1
        with:
          api_key: ${{ secrets.MUTEXBOT_API_KEY_TEST_COMPONENT_B }}
          mode: release
          resource_name: test-resource
          isolation_channel: ${{ vars.MUTEXBOT_CHANNEL_TESTING }}

      - name: Reduce reservation as component A
        uses: ./mutexbot
        with:
          api_key: ${{ secrets.MUTEXBOT_API_KEY_TEST_COMPONENT_A }}
          mode: reserve
          duration: 10m
          resource_name: test-resource
          isolation_channel: ${{ vars.MUTEXBOT_CHANNEL_TESTING }}

      - name: Force release as component B
        uses: ./mutexbot
        with:
          api_key: ${{ secrets.MUTEXBOT_API_KEY_TEST_COMPONENT_B }}
          mode: force-release
          resource_name: test-resource
          isolation_channel: ${{ vars.MUTEXBOT_CHANNEL_TESTING }}
