on:
  pull_request:
    branches:
      - main
    paths:
      - "release-pr/**"

defaults:
  run:
    shell: bash -euxo pipefail {0}
    working-directory: ./release-pr

permissions: {}

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
        with:
          version: "0.6.16"
          python-version: "${{ matrix.python-version }}"

      - name: Install project
        run: uv sync --locked --dev

      - run: uv run ruff check --output-format=github .
      - run: uv run ruff format --check .
      - run: uv run pyright
      - run: uv build
